services:
  # Django backend service
  - type: web
    name: app-dev-flutter-app
    runtime: python
    buildCommand: ./backend/build.sh
    startCommand: cd backend && daphne motion_detector_backend.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: DATABASE_URL
        value: postgresql://motion_detector_user:NBvmpfLaqH2AH4BE0P93VIdigkOn016U@dpg-d0k5uiffte5s738cqqa0-a.oregon-postgres.render.com/motion_detector
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: SITE_DOMAIN
        value: app-dev-flutter-app.onrender.com
      - key: FRONTEND_URL
        value: https://app-dev-flutter-app.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0
