[build]
  base = "web_app/motion-detector-react"
  publish = "dist"
  command = "npm run build"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[context.production.environment]
  VITE_API_BASE_URL = "https://app-dev-flutter-app.onrender.com"
  VITE_WS_BASE_URL = "wss://app-dev-flutter-app.onrender.com/ws"
