# Generated by Django 5.1.6 on 2025-05-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, help_text='Authentication token for device access', max_length=100, null=True),
        ),
    ]
